/**
 * webapp tool — สร้าง HTML app/game หรือ run Python script แล้ววาง link ให้ user เปิดเล่น
 *
 * Actions:
 * - create: สร้าง app จาก HTML หรือ Python code → serve ที่ /app/{id}.html → ส่ง link ให้ user
 *
 * Modes:
 * - language: "html" → save HTML ตรงๆ (เกม, quiz, calculator)
 * - language: "python" → run ใน subprocess → จับ output เป็น HTML (เหมือน Jupyter)
 */

import { mkdirSync, writeFileSync, rmSync, unlinkSync, readdirSync, existsSync, statSync } from "node:fs";
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import path from "node:path";
import type { ToolDefinition, ToolContext } from "./types.js";

import { getDb } from "../memory/store.js";

const APPS_DIR = "./data/apps";
const CLEANUP_HOURS = 24; // auto-delete non-pinned apps after 24h

// Ensure apps dir + DB table exist on startup
try { mkdirSync(APPS_DIR, { recursive: true }); } catch { /* ignore */ }

export function ensureAppsTable(dataDir: string): void {
  const db = getDb(dataDir);
  db.exec(`
    CREATE TABLE IF NOT EXISTS apps (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      language TEXT NOT NULL DEFAULT 'html',
      category TEXT NOT NULL DEFAULT 'other',
      size INTEGER DEFAULT 0,
      pinned INTEGER DEFAULT 0,
      user_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    )
  `);
  // Migration: add category column if table existed before
  try { db.exec("ALTER TABLE apps ADD COLUMN category TEXT NOT NULL DEFAULT 'other'"); } catch { /* already exists */ }
}

// Startup cleanup — ลบ non-pinned apps ที่เก่ากว่า CLEANUP_HOURS
try {
  const dataDir = process.env.DATA_DIR || "./data";
  ensureAppsTable(dataDir);
  const db = getDb(dataDir);

  // Get non-pinned apps older than threshold
  const old = db.prepare(
    `SELECT id FROM apps WHERE pinned = 0 AND created_at < datetime('now', '-${CLEANUP_HOURS} hours')`
  ).all() as Array<{ id: string }>;

  for (const row of old) {
    const fp = path.join(APPS_DIR, `${row.id}.html`);
    try { unlinkSync(fp); } catch { /* file may already be gone */ }
    db.prepare("DELETE FROM apps WHERE id = ?").run(row.id);
    console.log(`[webapp] Cleanup: removed non-pinned app ${row.id}`);
  }

  // Register orphan files (exist on disk but not in DB) — อย่าลบ เพราะอาจเป็น app เก่าจากก่อนมี DB
  for (const f of readdirSync(APPS_DIR)) {
    if (!f.endsWith(".html")) continue;
    const fid = f.replace(/\.html$/, "");
    const inDb = db.prepare("SELECT id FROM apps WHERE id = ?").get(fid);
    if (!inDb) {
      try {
        const stat = statSync(path.join(APPS_DIR, f));
        db.prepare(
          "INSERT INTO apps (id, title, language, category, size, pinned, created_at) VALUES (?, ?, 'html', 'other', ?, 0, ?)"
        ).run(fid, fid, stat.size, new Date(stat.birthtimeMs).toISOString().replace("T", " ").substring(0, 19));
        console.log(`[webapp] Registered orphan file ${f} into DB`);
      } catch { /* ignore */ }
    }
  }
} catch (err) {
  console.error("[webapp] Startup cleanup error:", err);
}

const PYTHON_TIMEOUT = 30_000; // 30 seconds
const MAX_OUTPUT = 10 * 1024 * 1024; // 10MB

function escHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function wrapOutputHtml(title: string, stdout: string, stderr: string): string {
  return `<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escHtml(title)}</title>
</head>
<body class="bg-[#1a1a2e] text-gray-200 font-mono p-5 leading-relaxed w-full min-h-screen">
<h3 class="text-violet-400 mb-3 text-lg">${escHtml(title)}</h3>
<pre class="whitespace-pre-wrap break-words bg-[#0f0f1a] p-4 rounded-lg text-sm overflow-x-auto">${escHtml(stdout)}</pre>
${stderr ? `<pre class="whitespace-pre-wrap break-words bg-[#0f0f1a] p-4 rounded-lg text-sm overflow-x-auto text-red-400 mt-3">${escHtml(stderr)}</pre>` : ""}
<p class="text-gray-600 text-xs mt-4">Generated by MyClaw</p>
</body>
</html>`;
}

// Tailwind CDN + minimal custom styles for injected components only
const INJECT_CSS = `
<script src="https://cdn.tailwindcss.com"></script>
<script>
tailwind.config = {
  theme: { extend: { colors: { surface: '#0f0f1a', dim: '#1a1a2e' } } }
}
</script>
<style id="mc-base">
/* touch-action for anti-zoom on rapid taps */
html,body,button,input,select,textarea{touch-action:manipulation}
html{-webkit-text-size-adjust:100%}
body{-webkit-tap-highlight-color:transparent}
/* D-pad touch controls — needs touch-action:none for precise game input */
.mc-dpad button{touch-action:none}
.mc-dpad .empty{background:none!important;border:none!important}
</style>
`;

const BACK_BUTTON_HTML = `<button class="fixed top-2 left-2 z-[99999] bg-black/55 text-white border-none rounded-full w-8 h-8 text-base cursor-pointer flex items-center justify-center backdrop-blur opacity-50 active:opacity-100 shadow-lg" onclick="(function(){try{window.close()}catch(e){}setTimeout(function(){location.href='https://line.me/R/'},300)})()" title="กลับ LINE">✕</button>`;

// JS ที่ inject: auto-resize canvas + auto-add touch controls (ไม่ดัก touch event ระดับ document)
const INJECT_JS = `
<script id="mc-helper">
(function(){
  // === Auto-resize canvas ให้พอดี viewport ===
  function fitCanvas(){
    var cs = document.querySelectorAll('canvas');
    if(!cs.length) return;
    cs.forEach(function(c){
      var maxW = window.innerWidth - 8;
      var maxH = window.innerHeight * 0.55;
      if(c.offsetWidth > maxW || c.offsetHeight > maxH){
        var ratio = Math.min(maxW / (c.width||300), maxH / (c.height||300));
        c.style.width = Math.floor((c.width||300)*ratio)+'px';
        c.style.height = Math.floor((c.height||300)*ratio)+'px';
        c.style.display = 'block';
        c.style.margin = '0 auto';
      }
    });
  }

  // === Auto-add touch D-pad ถ้ามี canvas แต่ไม่มี touch buttons ===
  function addTouchControls(){
    var cs = document.querySelectorAll('canvas');
    if(!cs.length) return;
    var existingBtns = document.querySelectorAll('button');
    // นับเฉพาะปุ่มที่ไม่ใช่ back button (ที่มี fixed+rounded-full)
    var gameBtns = 0;
    existingBtns.forEach(function(b){ if(!b.classList.contains('fixed') && !b.closest('.mc-dpad')) gameBtns++; });
    if(gameBtns >= 3) return;

    var dpad = document.createElement('div');
    dpad.className = 'mc-dpad fixed bottom-4 left-1/2 -translate-x-1/2 z-[99998] grid grid-cols-3 gap-1 select-none';
    dpad.innerHTML =
      '<div class="empty w-14 h-14"></div><button class="w-14 h-14 bg-white/10 border border-white/20 rounded-xl text-white text-xl flex items-center justify-center" data-key="ArrowUp">▲</button><div class="empty w-14 h-14"></div>'+
      '<button class="w-14 h-14 bg-white/10 border border-white/20 rounded-xl text-white text-xl flex items-center justify-center active:bg-indigo-500/40" data-key="ArrowLeft">◀</button>'+
      '<button class="w-14 h-14 bg-white/10 border border-white/20 rounded-xl text-white text-xl flex items-center justify-center active:bg-indigo-500/40" data-key="ArrowDown">▼</button>'+
      '<button class="w-14 h-14 bg-white/10 border border-white/20 rounded-xl text-white text-xl flex items-center justify-center active:bg-indigo-500/40" data-key="ArrowRight">▶</button>';
    document.body.appendChild(dpad);

    dpad.querySelectorAll('button').forEach(function(btn){
      function fire(type){
        var ev = new KeyboardEvent(type, {key:btn.dataset.key, code:btn.dataset.key, bubbles:true});
        document.dispatchEvent(ev);
      }
      btn.addEventListener('touchstart', function(e){e.preventDefault();fire('keydown')}, {passive:false});
      btn.addEventListener('touchend', function(e){e.preventDefault();fire('keyup')}, {passive:false});
      btn.addEventListener('mousedown', function(){fire('keydown')});
      btn.addEventListener('mouseup', function(){fire('keyup')});
    });
  }

  // Run after page load
  if(document.readyState==='loading'){
    document.addEventListener('DOMContentLoaded', function(){setTimeout(function(){fitCanvas();addTouchControls()},100)});
  } else {
    setTimeout(function(){fitCanvas();addTouchControls()},100);
  }
})();
</script>
`;

function injectIntoHtml(html: string): string {
  // 1. Ensure viewport meta exists
  if (!/name\s*=\s*["']viewport/i.test(html)) {
    const headEnd = html.indexOf("</head>");
    if (headEnd >= 0) {
      html = html.slice(0, headEnd) +
        '<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">\n' +
        html.slice(headEnd);
    }
  }

  // 2. Inject base CSS — right before </head>
  const headEndIdx = html.indexOf("</head>");
  if (headEndIdx >= 0) {
    html = html.slice(0, headEndIdx) + INJECT_CSS + html.slice(headEndIdx);
  } else {
    html = INJECT_CSS + html;
  }

  // 3. Inject back button — right after <body>
  const bodyMatch = html.match(/<body[^>]*>/i);
  if (bodyMatch) {
    const idx = html.indexOf(bodyMatch[0]) + bodyMatch[0].length;
    html = html.slice(0, idx) + BACK_BUTTON_HTML + html.slice(idx);
  } else {
    html = BACK_BUTTON_HTML + html;
  }

  // 4. Inject helper JS — right before </body>
  const bodyEndIdx = html.indexOf("</body>");
  if (bodyEndIdx >= 0) {
    html = html.slice(0, bodyEndIdx) + INJECT_JS + html.slice(bodyEndIdx);
  } else {
    html = html + INJECT_JS;
  }

  return html;
}

export const webappTool: ToolDefinition = {
  name: "webapp",
  description:
    "Generate an interactive web app, game, or run Python code and return a shareable URL. " +
    'Use language "html" for games/interactive UI (Tetris, Snake, quiz, calculator). ' +
    'Use language "python" to run Python scripts and show output (computation, data processing, charts). ' +
    "IMPORTANT: Include the app URL in your response so the user can open it. " +
    "Format: '🔗 [title]\\n[URL]\\n\\n[brief description of what you created]'. " +
    "ALWAYS create a new app — never reuse old URLs from conversation history (old files expire and get deleted).\n\n" +
    "CRITICAL: ALL apps/games MUST be FULLSCREEN on mobile — like a native app. Viewed in LINE in-app browser (~390×844px). " +
    "Fill 100% of the screen — NO margins, NO gaps, NO wasted space.\n\n" +
    "DESIGN REFERENCE (follow this style for ALL apps):\n" +
    "- Layout: header (score/info) at top → main content fills middle → controls at bottom. All edge-to-edge, no side margins.\n" +
    "- Buttons: LARGE (grid of big rounded squares filling full width), easy to tap with thumbs. Like a calculator app.\n" +
    "- Game controls: d-pad/action buttons should be BIG (min 60px), spread across full width at bottom.\n" +
    "- Score/status: compact header bar, one line, full width.\n" +
    "- Canvas/game area: fills ALL remaining space between header and controls.\n" +
    "- Overall feel: premium dark mobile game, not a desktop page shrunk to fit.\n\n" +
    "HTML rules — Tailwind CSS is auto-injected via CDN. USE TAILWIND UTILITY CLASSES for ALL styling:\n" +
    "- Body: 'm-0 p-0 overflow-hidden w-full h-screen flex flex-col'. NO max-width caps.\n" +
    "- Dark theme: bg-[#0f0f1a] text-gray-200 on body. Accent: violet-400, indigo-500.\n" +
    "- Canvas: canvas.width = window.innerWidth, canvas.height = remaining viewport. " +
    "NEVER cap width. NEVER add padding/margin. display:block; width:100%.\n" +
    "- Touch: large buttons min-h-[60px]. Full-width control bar at bottom, no side margins. gap-1 or gap-2 between buttons.\n" +
    "- Buttons: 'bg-gray-700/80 text-white rounded-xl text-xl active:bg-gray-600 shadow-lg'. Accent for special buttons.\n" +
    "- NO custom CSS. ONLY Tailwind utilities + inline JS for dynamic sizing.\n" +
    "- No external deps besides Tailwind (auto-injected). All JS inline.\n" +
    "- Thai UI labels when user speaks Thai.",
  inputSchema: {
    type: "object" as const,
    properties: {
      action: {
        type: "string",
        enum: ["create"],
        description: "Action to perform.",
      },
      language: {
        type: "string",
        enum: ["html", "python"],
        description: '"html" for web apps/games (self-contained HTML), "python" for script execution.',
      },
      title: {
        type: "string",
        description: "App/script title for display.",
      },
      category: {
        type: "string",
        enum: ["game", "tool", "quiz", "art", "data", "other"],
        description: 'App category: "game" (Snake, Tetris), "tool" (calculator, converter), "quiz" (trivia, test), "art" (drawing, animation), "data" (charts, analysis), "other".',
      },
      code: {
        type: "string",
        description: "Complete HTML content (for html) or Python script (for python). Must be self-contained.",
      },
    },
    required: ["action", "language", "code"],
  },

  execute: async (
    input: Record<string, unknown>,
    context?: ToolContext,
  ): Promise<string> => {
    const language = input.language as string;
    const title = (input.title as string) || "MyClaw App";
    const category = (input.category as string) || "other";
    const code = input.code as string;

    if (!code) return JSON.stringify({ error: "code is required" });
    if (!["html", "python"].includes(language)) {
      return JSON.stringify({ error: 'language must be "html" or "python"' });
    }

    const baseUrl = process.env.BASE_URL?.trim();
    if (!baseUrl) return JSON.stringify({ error: "BASE_URL not configured yet — send any LINE message first" });

    const id = randomBytes(8).toString("hex");

    try {
      mkdirSync(APPS_DIR, { recursive: true });

      let htmlContent: string;

      if (language === "python") {
        // === Python sandbox mode ===
        const tmpDir = path.join(APPS_DIR, `tmp_${id}`);
        mkdirSync(tmpDir, { recursive: true });
        const scriptPath = path.join(tmpDir, "script.py");
        writeFileSync(scriptPath, code);

        let stdout = "";
        let stderr = "";
        let exitCode = 0;

        try {
          const output = execSync(`python3 "${scriptPath}"`, {
            timeout: PYTHON_TIMEOUT,
            stdio: "pipe",
            cwd: tmpDir,
            maxBuffer: MAX_OUTPUT,
          });
          stdout = output.toString();
        } catch (execErr: any) {
          exitCode = execErr.status ?? 1;
          stdout = execErr.stdout?.toString() || "";
          stderr = execErr.stderr?.toString() || "";
          if (execErr.killed || execErr.signal === "SIGTERM") {
            stderr = `Script timeout (${PYTHON_TIMEOUT / 1000}s limit exceeded)\n${stderr}`;
          }
        }

        // Cleanup temp dir
        try { rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }

        // ถ้า stdout เป็น HTML สมบูรณ์ → ใช้เลย
        if (stdout.trim().toLowerCase().startsWith("<!doctype html") || stdout.trim().toLowerCase().startsWith("<html")) {
          htmlContent = stdout;
        } else {
          htmlContent = wrapOutputHtml(title, stdout || "(no output)", stderr);
        }

        console.log(`[webapp] Python executed: exit=${exitCode}, stdout=${stdout.length}B, stderr=${stderr.length}B`);
      } else {
        // === HTML mode ===
        htmlContent = code;
      }

      // Inject base CSS + viewport + back button
      htmlContent = injectIntoHtml(htmlContent);

      // Save HTML
      const filename = `${id}.html`;
      const filepath = path.join(APPS_DIR, filename);
      writeFileSync(filepath, htmlContent);

      const appUrl = `${baseUrl.replace(/\/$/, "")}/app/${filename}`;
      console.log(`[webapp] Created: ${filename} (${language}, ${(htmlContent.length / 1024).toFixed(1)}KB)`);

      // Save to DB for admin tracking
      try {
        const dataDir = process.env.DATA_DIR || "./data";
        ensureAppsTable(dataDir);
        getDb(dataDir).prepare(
          "INSERT OR REPLACE INTO apps (id, title, language, category, size, user_id) VALUES (?, ?, ?, ?, ?, ?)"
        ).run(id, title, language, category, htmlContent.length, context?.userId || null);
      } catch { /* non-critical */ }

      return JSON.stringify({
        success: true,
        appUrl,
        appId: id,
        language,
        title,
        size: htmlContent.length,
        note: "IMPORTANT: Include the URL in your response so the user can open the app. Format: 🔗 title\\nURL\\n\\n(brief description)",
      });
    } catch (err: any) {
      console.error("[webapp] create error:", err);
      return JSON.stringify({ error: err?.message || "create failed" });
    }
  },
};
